"""Render a Mermaid .mmd file to an image (PNG/SVG) or HTML.

Rendering strategy (in priority order):
1. mmdc (Mermaid CLI) — if available, renders directly to PNG/SVG
2. HTML fallback — generates a self-contained HTML file for browser viewing

Usage:
    # From file:
    python scripts/render_diagram.py <input.mmd> [--output <output>] [--format png|svg|html]

    # From stdin (for sandbox use where workspace is read-only):
    echo 'mindmap\n  root((Topic))' | python scripts/render_diagram.py --stdin [--name diagram] [--format png]

Sandbox notes:
- When running in Docker sandbox, the workspace is mounted read-only.
- Use --stdin mode with the 'input' parameter of execute_skill_script to pass
  Mermaid content directly without needing to create a file first.
- Output files are written to /output (if mounted) or /tmp.
- mmdc requires `-p /etc/mermaid-cli/puppeteer-config.json` in sandbox.
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import shutil
import subprocess
import sys


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{
    margin: 0;
    padding: 24px;
    background: white;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }}
  .container {{
    max-width: 1200px;
    margin: 0 auto;
  }}
  .header {{
    margin-bottom: 16px;
    padding-bottom: 12px;
    border-bottom: 1px solid #e5e7eb;
  }}
  .header h1 {{
    font-size: 18px;
    font-weight: 600;
    color: #111827;
    margin: 0;
  }}
  .header .meta {{
    font-size: 12px;
    color: #6b7280;
    margin-top: 4px;
  }}
  .diagram {{
    display: flex;
    justify-content: center;
    padding: 24px;
    background: #fafafa;
    border-radius: 8px;
    border: 1px solid #e5e7eb;
  }}
  .source {{
    margin-top: 16px;
    padding: 16px;
    background: #f8f9fa;
    border-radius: 8px;
    border: 1px solid #e5e7eb;
  }}
  .source summary {{
    cursor: pointer;
    font-size: 13px;
    color: #6b7280;
    font-weight: 500;
  }}
  .source pre {{
    margin: 8px 0 0 0;
    padding: 12px;
    background: #1e293b;
    color: #e2e8f0;
    border-radius: 6px;
    font-size: 13px;
    line-height: 1.5;
    overflow-x: auto;
  }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>{title}</h1>
    <div class="meta">Source: {source_file} &middot; Generated by mindmap-diagram-v3</div>
  </div>
  <div class="diagram">
    <pre class="mermaid">
{mermaid_code}
    </pre>
  </div>
  <details class="source">
    <summary>View Mermaid Source Code</summary>
    <pre><code>{escaped_code}</code></pre>
  </details>
</div>
{mermaid_script}
</body>
</html>"""


MERMAID_INIT_SCRIPT = """<script>
  mermaid.initialize({{
    startOnLoad: true,
    theme: 'default',
    securityLevel: 'loose',
    flowchart: {{ useMaxWidth: true, htmlLabels: true, curve: 'basis' }},
    mindmap: {{ useMaxWidth: true }},
    sequence: {{ useMaxWidth: true }},
    timeline: {{ useMaxWidth: true }},
  }});
</script>"""

# Local paths for mermaid.js (offline, inside Docker sandbox)
_MERMAID_LOCAL_PATHS = [
    "/usr/local/share/mermaid/mermaid.min.js",  # Installed in sandbox image
    "/usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/@mermaid-js/mermaid/dist/mermaid.min.js",
]


def escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def is_mmdc_available() -> str | None:
    """Check if mmdc (Mermaid CLI) is available. Returns path or None."""
    return shutil.which("mmdc")


def get_output_dir(input_path: str | None = None) -> str:
    """Determine a writable output directory.

    Priority:
    1. /output — Docker sandbox mounted output directory
    2. Source directory — if writable (and input_path is provided)
    3. /tmp — fallback
    """
    # Check for Docker sandbox output mount first
    if os.path.isdir("/output"):
        return "/output"

    if input_path:
        source_dir = os.path.dirname(os.path.abspath(input_path))
        test_file = os.path.join(source_dir, ".write_test")
        try:
            with open(test_file, "w") as f:
                f.write("test")
            os.remove(test_file)
            return source_dir
        except OSError:
            pass

    return "/tmp"


def find_local_mermaid_js() -> str | None:
    """Find a local mermaid.min.js file for offline rendering.

    Checks known paths inside the Docker sandbox image first,
    then searches common system locations.
    Returns the file path if found, None otherwise.
    """
    for path in _MERMAID_LOCAL_PATHS:
        if os.path.isfile(path):
            return path
    return None


def build_mermaid_script_tag(mermaid_js_path: str | None = None) -> str:
    """Build the <script> tag(s) for loading mermaid.js.

    Priority:
    1. Inline mermaid.js from local file (fully offline)
    2. Reference local file via file:// path
    3. CDN fallback (online only)
    """
    if mermaid_js_path and os.path.isfile(mermaid_js_path):
        with open(mermaid_js_path, "r", encoding="utf-8") as f:
            js_content = f.read()
        return f'<script>\n{js_content}\n</script>\n{MERMAID_INIT_SCRIPT}'
    else:
        # CDN fallback — only works online
        return (
            '<script type="module">\n'
            "  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';\n"
            '  mermaid.initialize({{\n'
            "    startOnLoad: true,\n"
            "    theme: 'default',\n"
            "    securityLevel: 'loose',\n"
            '    flowchart: {{ useMaxWidth: true, htmlLabels: true, curve: \"basis\" }},\n'
            '    mindmap: {{ useMaxWidth: true }},\n'
            '    sequence: {{ useMaxWidth: true }},\n'
            '    timeline: {{ useMaxWidth: true }},\n'
            '  }});\n'
            '</script>'
        )


def render_to_html(mermaid_code: str, title: str = "Diagram",
                  source_file: str = "stdin",
                  output_path: str | None = None) -> str:
    """Render Mermaid content to an HTML file (fallback method).

    Args:
        mermaid_code: The Mermaid diagram content.
        title: Title for the HTML page.
        source_file: Name of the source file (for display).
        output_path: Optional output HTML path.

    Returns:
        Path to the generated HTML file.
    """
    if not mermaid_code.strip():
        print("Error: Mermaid content is empty", file=sys.stderr)
        sys.exit(1)

    if output_path is None:
        out_dir = get_output_dir()
        safe_title = title.replace(" ", "-").replace("/", "-")
        output_path = os.path.join(out_dir, safe_title + ".html")

    html = HTML_TEMPLATE.format(
        title=title,
        source_file=source_file,
        mermaid_code=mermaid_code.strip(),
        escaped_code=escape_html(mermaid_code.strip()),
        mermaid_script=build_mermaid_script_tag(find_local_mermaid_js()),
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    return output_path


def render_with_mmdc(mermaid_code: str, title: str = "Diagram",
                     output_path: str | None = None,
                     fmt: str = "png", width: int = 1600) -> str:
    """Render Mermaid content using mmdc (Mermaid CLI).

    Args:
        mermaid_code: The Mermaid diagram content.
        title: Title / base name for output files.
        output_path: Optional output path.
        fmt: Output format (png or svg).
        width: Output width in pixels.

    Returns:
        Path to the generated image file.
    """
    out_dir = get_output_dir()

    # Write mermaid content to a temp .mmd file (mmdc requires a file input)
    safe_title = title.replace(" ", "-").replace("/", "-")
    mmd_path = os.path.join(out_dir, safe_title + ".mmd")
    with open(mmd_path, "w", encoding="utf-8") as f:
        f.write(mermaid_code.strip())

    if output_path is None:
        output_path = os.path.join(out_dir, safe_title + "." + fmt)

    # Build mmdc command
    cmd = [
        "mmdc",
        "-p", "/etc/mermaid-cli/puppeteer-config.json",
        "-i", mmd_path,
        "-o", output_path,
        "-w", str(width),
        "-b", "white",
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode != 0:
            print(f"mmdc warning: {result.stderr}", file=sys.stderr)
            # Fall back to HTML
            return render_to_html(mermaid_code, title, output_path.rsplit(".", 1)[0] + ".html")
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        print(f"mmdc not available: {e}", file=sys.stderr)
        return render_to_html(mermaid_code, title, output_path.rsplit(".", 1)[0] + ".html")

    return output_path


def output_result(output_path: str, fmt: str) -> None:
    """Print the rendering result as JSON to stdout for the agent to consume."""
    result = {
        "output_file": output_path,
        "format": fmt,
    }

    if os.path.isfile(output_path) and fmt in ("png", "svg"):
        # For image files, also output base64 for embedding
        with open(output_path, "rb") as f:
            data = f.read()
        result["size_bytes"] = len(data)
        result["base64"] = base64.b64encode(data).decode("ascii")
    elif os.path.isfile(output_path) and fmt == "html":
        with open(output_path, "r", encoding="utf-8") as f:
            result["content"] = f.read()
        result["size_bytes"] = os.path.getsize(output_path)

    print(json.dumps(result, ensure_ascii=False, indent=2))


def main():
    parser = argparse.ArgumentParser(
        description="Render Mermaid content to PNG/SVG (via mmdc) or HTML (fallback). "
                    "Supports input from a file or stdin (--stdin)."
    )
    parser.add_argument(
        "input", nargs="?", default=None,
        help="Path to the .mmd source file (optional if --stdin is used)",
    )
    parser.add_argument(
        "--stdin", action="store_true",
        help="Read Mermaid content from stdin instead of a file. "
             "Use with execute_skill_script 'input' parameter.",
    )
    parser.add_argument(
        "--name", default="diagram",
        help="Base name for output files when using --stdin (default: diagram)",
    )
    parser.add_argument(
        "-o", "--output",
        help="Output file path (default: auto-generated in /output or /tmp)",
    )
    parser.add_argument(
        "-f", "--format",
        choices=["png", "svg", "html"],
        default=None,
        help="Output format (default: auto-detect — png if mmdc available, html otherwise)",
    )
    parser.add_argument(
        "-w", "--width",
        type=int,
        default=1600,
        help="Output width in pixels (default: 1600)",
    )
    args = parser.parse_args()

    # Determine mermaid content source
    mermaid_code = ""
    title = args.name
    source_file = args.name + ".mmd"

    if args.stdin:
        # Read from stdin — the primary mode for sandbox execution
        mermaid_code = sys.stdin.read()
        if not mermaid_code.strip():
            print("Error: No Mermaid content received from stdin", file=sys.stderr)
            sys.exit(1)
    elif args.input:
        if not os.path.isfile(args.input):
            print(f"Error: Input file not found: {args.input}", file=sys.stderr)
            sys.exit(1)
        with open(args.input, "r", encoding="utf-8") as f:
            mermaid_code = f.read()
        title = os.path.splitext(os.path.basename(args.input))[0]
        title = title.replace("-", " ").replace("_", " ").title()
        source_file = os.path.basename(args.input)
    else:
        parser.error("Either provide an input file or use --stdin")

    # Determine format
    fmt = args.format
    if fmt is None:
        fmt = "png" if is_mmdc_available() else "html"

    # Render
    if fmt == "html":
        output_path = render_to_html(mermaid_code, title, source_file, args.output)
    else:
        if not is_mmdc_available():
            print("mmdc not available, falling back to HTML", file=sys.stderr)
            fmt = "html"
            output_path = render_to_html(mermaid_code, title, source_file, args.output)
        else:
            output_path = render_with_mmdc(mermaid_code, title, args.output, fmt, args.width)

    # Print result info
    print(f"Rendered: {output_path}", file=sys.stderr)
    output_result(output_path, fmt)


if __name__ == "__main__":
    main()
